version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    hostname: mariadb
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ideationbankdb
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - "3306"